### ISSUE TITLE
24-bit versus 32-bit performance (GPMC)

### ISSUE THREAD

**Issue by buffeebeta** [nonarkitten/pseudo-jit#20]
It has been proven that big-endian mode works on the AM3358 with two exceptions -- all peripheral IO has to be endian-swapped when reading/writing registers and the GPMC is simply broken and will only work in little-endian mode. This has necessitated two workarounds:
```
eor rA, rA, #1
```
For accessing bytes in their correct order, and;
```
ror rD, rD,#16
```
To place words back into their correct order when reading/writing 32-bit data (and with read-modify-write operations, this has to be done twice).

An alternate option is to disable the GPMC and use "bit-banging." This would allow us full control over the bus and timing (though strict 68000 timing may be a challenge) without the need for the GreenPAK and has the interesting side-effect of no longer needing the GreenPAK.

24-bit address memory would be set up as a trap space for the MMU, triggering a data abort, which would then perform the memory operation manually before returning.

32-bit address memory would then be accessed using big-endian mode and neither the ```eor``` or ```ror``` above would be required, significantly speeding up access.

Good:
- much faster 32-bit performance
- easily reprogrammable timing parameters
- allows the Alpha-boards to be used
- allows the GreenPAK to be removed

Bad:
- much slower 24-bit performance
- loss of ARM-side DMA (which to be fair, isn't a "thing" yet)

Ugly:
- might be too slow to actually work (need to be inside ~500 cycles!)
- cannot use Code Composer Studio for this as it "forbids" big-endian on ARM

**Comment by nonarkitten** [comment]
It has been proven that the problem with big-endian is Code Composer Studio, not the GPMC or anything else. This means we no longer need an in-code fix, just a more concrete CCS fix.
